# Generated by Django 4.2 on 2023-04-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('descrption', models.CharField(max_length=150)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
